# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'Kairos' do

# Database
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'

# Facebook
pod 'FBSDKLoginKit'

# Calendar Library
pod 'JTAppleCalendar', '~> 6.0'

end

target 'KairosTests' do

end

target 'KairosUITests' do

end

