# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'Kairos' do

# Database
pod 'Firebase/Core'

# Facebook
pod 'FBSDKLoginKit'

end

target 'KairosTests' do

end

target 'KairosUITests' do

end

